//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kyc.bridge.api.BankBvnService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BankBvnService.BVNProcessorSoap")]
    public interface BVNProcessorSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerifySingleBVN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string VerifySingleBVN(string BVN, string bankcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerifySingleBVN", ReplyAction="*")]
        System.Threading.Tasks.Task<string> VerifySingleBVNAsync(string BVN, string bankcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerifyMultipleBVN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string VerifyMultipleBVN(string BVN, string bankcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerifyMultipleBVN", ReplyAction="*")]
        System.Threading.Tasks.Task<string> VerifyMultipleBVNAsync(string BVN, string bankcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BVNUpdateCustomerDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string BVNUpdateCustomerDetails(kyc.bridge.api.BankBvnService.UpdateDetail myCustUpt, string bankcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BVNUpdateCustomerDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<string> BVNUpdateCustomerDetailsAsync(kyc.bridge.api.BankBvnService.UpdateDetail myCustUpt, string bankcode);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bVNField;
        
        private Email emailField;
        
        private FirstName firstNameField;
        
        private Gender genderField;
        
        private LastName lastNameField;
        
        private LevelOfAccount levelOfAccountField;
        
        private LgaOfOrigin lgaOfOriginField;
        
        private LgaOfResidence lgaOfResidenceField;
        
        private MaritalStatus maritalStatusField;
        
        private MiddleName middleNameField;
        
        private NIN nINField;
        
        private NameOnCard nameOnCardField;
        
        private Nationality nationalityField;
        
        private PhoneNumber1 phoneNumber1Field;
        
        private PhoneNumber2 phoneNumber2Field;
        
        private ResidentialAddress residentialAddressField;
        
        private StateOfOrigin stateOfOriginField;
        
        private StateOfResidence stateOfResidenceField;
        
        private Title titleField;
        
        private DateOfBirth dateOfBirthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BVN {
            get {
                return this.bVNField;
            }
            set {
                this.bVNField = value;
                this.RaisePropertyChanged("BVN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Email Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public FirstName FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Gender Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("Gender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public LastName LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public LevelOfAccount LevelOfAccount {
            get {
                return this.levelOfAccountField;
            }
            set {
                this.levelOfAccountField = value;
                this.RaisePropertyChanged("LevelOfAccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public LgaOfOrigin LgaOfOrigin {
            get {
                return this.lgaOfOriginField;
            }
            set {
                this.lgaOfOriginField = value;
                this.RaisePropertyChanged("LgaOfOrigin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public LgaOfResidence LgaOfResidence {
            get {
                return this.lgaOfResidenceField;
            }
            set {
                this.lgaOfResidenceField = value;
                this.RaisePropertyChanged("LgaOfResidence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public MaritalStatus MaritalStatus {
            get {
                return this.maritalStatusField;
            }
            set {
                this.maritalStatusField = value;
                this.RaisePropertyChanged("MaritalStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public MiddleName MiddleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
                this.RaisePropertyChanged("MiddleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public NIN NIN {
            get {
                return this.nINField;
            }
            set {
                this.nINField = value;
                this.RaisePropertyChanged("NIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public NameOnCard NameOnCard {
            get {
                return this.nameOnCardField;
            }
            set {
                this.nameOnCardField = value;
                this.RaisePropertyChanged("NameOnCard");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public Nationality Nationality {
            get {
                return this.nationalityField;
            }
            set {
                this.nationalityField = value;
                this.RaisePropertyChanged("Nationality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public PhoneNumber1 PhoneNumber1 {
            get {
                return this.phoneNumber1Field;
            }
            set {
                this.phoneNumber1Field = value;
                this.RaisePropertyChanged("PhoneNumber1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public PhoneNumber2 PhoneNumber2 {
            get {
                return this.phoneNumber2Field;
            }
            set {
                this.phoneNumber2Field = value;
                this.RaisePropertyChanged("PhoneNumber2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public ResidentialAddress ResidentialAddress {
            get {
                return this.residentialAddressField;
            }
            set {
                this.residentialAddressField = value;
                this.RaisePropertyChanged("ResidentialAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public StateOfOrigin StateOfOrigin {
            get {
                return this.stateOfOriginField;
            }
            set {
                this.stateOfOriginField = value;
                this.RaisePropertyChanged("StateOfOrigin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public StateOfResidence StateOfResidence {
            get {
                return this.stateOfResidenceField;
            }
            set {
                this.stateOfResidenceField = value;
                this.RaisePropertyChanged("StateOfResidence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public Title Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public DateOfBirth DateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
                this.RaisePropertyChanged("DateOfBirth");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Email : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string oldEmailField;
        
        private string newEmailField;
        
        private string reasonForChangeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OldEmail {
            get {
                return this.oldEmailField;
            }
            set {
                this.oldEmailField = value;
                this.RaisePropertyChanged("OldEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NewEmail {
            get {
                return this.newEmailField;
            }
            set {
                this.newEmailField = value;
                this.RaisePropertyChanged("NewEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ReasonForChange {
            get {
                return this.reasonForChangeField;
            }
            set {
                this.reasonForChangeField = value;
                this.RaisePropertyChanged("ReasonForChange");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DateOfBirth : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string oldDateOfBirthField;
        
        private string newDateOfBirthField;
        
        private string reasonForChangeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OldDateOfBirth {
            get {
                return this.oldDateOfBirthField;
            }
            set {
                this.oldDateOfBirthField = value;
                this.RaisePropertyChanged("OldDateOfBirth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NewDateOfBirth {
            get {
                return this.newDateOfBirthField;
            }
            set {
                this.newDateOfBirthField = value;
                this.RaisePropertyChanged("NewDateOfBirth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ReasonForChange {
            get {
                return this.reasonForChangeField;
            }
            set {
                this.reasonForChangeField = value;
                this.RaisePropertyChanged("ReasonForChange");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Title : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string oldTitleField;
        
        private string newTitleField;
        
        private string reasonForChangeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OldTitle {
            get {
                return this.oldTitleField;
            }
            set {
                this.oldTitleField = value;
                this.RaisePropertyChanged("OldTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NewTitle {
            get {
                return this.newTitleField;
            }
            set {
                this.newTitleField = value;
                this.RaisePropertyChanged("NewTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ReasonForChange {
            get {
                return this.reasonForChangeField;
            }
            set {
                this.reasonForChangeField = value;
                this.RaisePropertyChanged("ReasonForChange");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StateOfResidence : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string oldStateOfResidenceField;
        
        private string newStateOfResidenceField;
        
        private string reasonForChangeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OldStateOfResidence {
            get {
                return this.oldStateOfResidenceField;
            }
            set {
                this.oldStateOfResidenceField = value;
                this.RaisePropertyChanged("OldStateOfResidence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NewStateOfResidence {
            get {
                return this.newStateOfResidenceField;
            }
            set {
                this.newStateOfResidenceField = value;
                this.RaisePropertyChanged("NewStateOfResidence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ReasonForChange {
            get {
                return this.reasonForChangeField;
            }
            set {
                this.reasonForChangeField = value;
                this.RaisePropertyChanged("ReasonForChange");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StateOfOrigin : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string oldStateOfOriginField;
        
        private string newStateOfOriginField;
        
        private string reasonForChangeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OldStateOfOrigin {
            get {
                return this.oldStateOfOriginField;
            }
            set {
                this.oldStateOfOriginField = value;
                this.RaisePropertyChanged("OldStateOfOrigin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NewStateOfOrigin {
            get {
                return this.newStateOfOriginField;
            }
            set {
                this.newStateOfOriginField = value;
                this.RaisePropertyChanged("NewStateOfOrigin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ReasonForChange {
            get {
                return this.reasonForChangeField;
            }
            set {
                this.reasonForChangeField = value;
                this.RaisePropertyChanged("ReasonForChange");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResidentialAddress : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string oldResidentialAddressField;
        
        private string newResidentialAddressField;
        
        private string reasonForChangeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OldResidentialAddress {
            get {
                return this.oldResidentialAddressField;
            }
            set {
                this.oldResidentialAddressField = value;
                this.RaisePropertyChanged("OldResidentialAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NewResidentialAddress {
            get {
                return this.newResidentialAddressField;
            }
            set {
                this.newResidentialAddressField = value;
                this.RaisePropertyChanged("NewResidentialAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ReasonForChange {
            get {
                return this.reasonForChangeField;
            }
            set {
                this.reasonForChangeField = value;
                this.RaisePropertyChanged("ReasonForChange");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PhoneNumber2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string oldPhoneNumber2Field;
        
        private string newPhoneNumber2Field;
        
        private string reasonForChangeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OldPhoneNumber2 {
            get {
                return this.oldPhoneNumber2Field;
            }
            set {
                this.oldPhoneNumber2Field = value;
                this.RaisePropertyChanged("OldPhoneNumber2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NewPhoneNumber2 {
            get {
                return this.newPhoneNumber2Field;
            }
            set {
                this.newPhoneNumber2Field = value;
                this.RaisePropertyChanged("NewPhoneNumber2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ReasonForChange {
            get {
                return this.reasonForChangeField;
            }
            set {
                this.reasonForChangeField = value;
                this.RaisePropertyChanged("ReasonForChange");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PhoneNumber1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string oldPhoneNumber1Field;
        
        private string newPhoneNumber1Field;
        
        private string reasonForChangeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OldPhoneNumber1 {
            get {
                return this.oldPhoneNumber1Field;
            }
            set {
                this.oldPhoneNumber1Field = value;
                this.RaisePropertyChanged("OldPhoneNumber1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NewPhoneNumber1 {
            get {
                return this.newPhoneNumber1Field;
            }
            set {
                this.newPhoneNumber1Field = value;
                this.RaisePropertyChanged("NewPhoneNumber1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ReasonForChange {
            get {
                return this.reasonForChangeField;
            }
            set {
                this.reasonForChangeField = value;
                this.RaisePropertyChanged("ReasonForChange");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Nationality : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string oldNationalityField;
        
        private string newNationalityField;
        
        private string reasonForChangeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OldNationality {
            get {
                return this.oldNationalityField;
            }
            set {
                this.oldNationalityField = value;
                this.RaisePropertyChanged("OldNationality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NewNationality {
            get {
                return this.newNationalityField;
            }
            set {
                this.newNationalityField = value;
                this.RaisePropertyChanged("NewNationality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ReasonForChange {
            get {
                return this.reasonForChangeField;
            }
            set {
                this.reasonForChangeField = value;
                this.RaisePropertyChanged("ReasonForChange");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NameOnCard : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string oldNameOnCardField;
        
        private string newNameOnCardField;
        
        private string reasonForChangeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OldNameOnCard {
            get {
                return this.oldNameOnCardField;
            }
            set {
                this.oldNameOnCardField = value;
                this.RaisePropertyChanged("OldNameOnCard");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NewNameOnCard {
            get {
                return this.newNameOnCardField;
            }
            set {
                this.newNameOnCardField = value;
                this.RaisePropertyChanged("NewNameOnCard");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ReasonForChange {
            get {
                return this.reasonForChangeField;
            }
            set {
                this.reasonForChangeField = value;
                this.RaisePropertyChanged("ReasonForChange");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NIN : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string oldNINField;
        
        private string newNINField;
        
        private string reasonForChangeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OldNIN {
            get {
                return this.oldNINField;
            }
            set {
                this.oldNINField = value;
                this.RaisePropertyChanged("OldNIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NewNIN {
            get {
                return this.newNINField;
            }
            set {
                this.newNINField = value;
                this.RaisePropertyChanged("NewNIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ReasonForChange {
            get {
                return this.reasonForChangeField;
            }
            set {
                this.reasonForChangeField = value;
                this.RaisePropertyChanged("ReasonForChange");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MiddleName : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string oldMiddleNameField;
        
        private string newMiddleNameField;
        
        private string reasonForChangeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OldMiddleName {
            get {
                return this.oldMiddleNameField;
            }
            set {
                this.oldMiddleNameField = value;
                this.RaisePropertyChanged("OldMiddleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NewMiddleName {
            get {
                return this.newMiddleNameField;
            }
            set {
                this.newMiddleNameField = value;
                this.RaisePropertyChanged("NewMiddleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ReasonForChange {
            get {
                return this.reasonForChangeField;
            }
            set {
                this.reasonForChangeField = value;
                this.RaisePropertyChanged("ReasonForChange");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MaritalStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string oldMaritalStatusField;
        
        private string newMaritalStatusField;
        
        private string reasonForChangeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OldMaritalStatus {
            get {
                return this.oldMaritalStatusField;
            }
            set {
                this.oldMaritalStatusField = value;
                this.RaisePropertyChanged("OldMaritalStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NewMaritalStatus {
            get {
                return this.newMaritalStatusField;
            }
            set {
                this.newMaritalStatusField = value;
                this.RaisePropertyChanged("NewMaritalStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ReasonForChange {
            get {
                return this.reasonForChangeField;
            }
            set {
                this.reasonForChangeField = value;
                this.RaisePropertyChanged("ReasonForChange");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LgaOfResidence : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string oldLgaOfResidenceField;
        
        private string newLgaOfResidenceField;
        
        private string reasonForChangeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OldLgaOfResidence {
            get {
                return this.oldLgaOfResidenceField;
            }
            set {
                this.oldLgaOfResidenceField = value;
                this.RaisePropertyChanged("OldLgaOfResidence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NewLgaOfResidence {
            get {
                return this.newLgaOfResidenceField;
            }
            set {
                this.newLgaOfResidenceField = value;
                this.RaisePropertyChanged("NewLgaOfResidence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ReasonForChange {
            get {
                return this.reasonForChangeField;
            }
            set {
                this.reasonForChangeField = value;
                this.RaisePropertyChanged("ReasonForChange");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LgaOfOrigin : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string oldLgaOfOriginField;
        
        private string newLgaOfOriginField;
        
        private string reasonForChangeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OldLgaOfOrigin {
            get {
                return this.oldLgaOfOriginField;
            }
            set {
                this.oldLgaOfOriginField = value;
                this.RaisePropertyChanged("OldLgaOfOrigin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NewLgaOfOrigin {
            get {
                return this.newLgaOfOriginField;
            }
            set {
                this.newLgaOfOriginField = value;
                this.RaisePropertyChanged("NewLgaOfOrigin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ReasonForChange {
            get {
                return this.reasonForChangeField;
            }
            set {
                this.reasonForChangeField = value;
                this.RaisePropertyChanged("ReasonForChange");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LevelOfAccount : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string oldLevelOfAccountField;
        
        private string newLevelOfAccountField;
        
        private string reasonForChangeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OldLevelOfAccount {
            get {
                return this.oldLevelOfAccountField;
            }
            set {
                this.oldLevelOfAccountField = value;
                this.RaisePropertyChanged("OldLevelOfAccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NewLevelOfAccount {
            get {
                return this.newLevelOfAccountField;
            }
            set {
                this.newLevelOfAccountField = value;
                this.RaisePropertyChanged("NewLevelOfAccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ReasonForChange {
            get {
                return this.reasonForChangeField;
            }
            set {
                this.reasonForChangeField = value;
                this.RaisePropertyChanged("ReasonForChange");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LastName : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string oldLastNameField;
        
        private string newLastNameField;
        
        private string reasonForChangeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OldLastName {
            get {
                return this.oldLastNameField;
            }
            set {
                this.oldLastNameField = value;
                this.RaisePropertyChanged("OldLastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NewLastName {
            get {
                return this.newLastNameField;
            }
            set {
                this.newLastNameField = value;
                this.RaisePropertyChanged("NewLastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ReasonForChange {
            get {
                return this.reasonForChangeField;
            }
            set {
                this.reasonForChangeField = value;
                this.RaisePropertyChanged("ReasonForChange");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Gender : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string oldGenderField;
        
        private string newGenderField;
        
        private string reasonForChangeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OldGender {
            get {
                return this.oldGenderField;
            }
            set {
                this.oldGenderField = value;
                this.RaisePropertyChanged("OldGender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NewGender {
            get {
                return this.newGenderField;
            }
            set {
                this.newGenderField = value;
                this.RaisePropertyChanged("NewGender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ReasonForChange {
            get {
                return this.reasonForChangeField;
            }
            set {
                this.reasonForChangeField = value;
                this.RaisePropertyChanged("ReasonForChange");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FirstName : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string oldFirstNameField;
        
        private string newFirstNameField;
        
        private string reasonForChangeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OldFirstName {
            get {
                return this.oldFirstNameField;
            }
            set {
                this.oldFirstNameField = value;
                this.RaisePropertyChanged("OldFirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NewFirstName {
            get {
                return this.newFirstNameField;
            }
            set {
                this.newFirstNameField = value;
                this.RaisePropertyChanged("NewFirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ReasonForChange {
            get {
                return this.reasonForChangeField;
            }
            set {
                this.reasonForChangeField = value;
                this.RaisePropertyChanged("ReasonForChange");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BVNProcessorSoapChannel : kyc.bridge.api.BankBvnService.BVNProcessorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BVNProcessorSoapClient : System.ServiceModel.ClientBase<kyc.bridge.api.BankBvnService.BVNProcessorSoap>, kyc.bridge.api.BankBvnService.BVNProcessorSoap {
        
        public BVNProcessorSoapClient() {
        }
        
        public BVNProcessorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BVNProcessorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BVNProcessorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BVNProcessorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string VerifySingleBVN(string BVN, string bankcode) {
            return base.Channel.VerifySingleBVN(BVN, bankcode);
        }
        
        public System.Threading.Tasks.Task<string> VerifySingleBVNAsync(string BVN, string bankcode) {
            return base.Channel.VerifySingleBVNAsync(BVN, bankcode);
        }
        
        public string VerifyMultipleBVN(string BVN, string bankcode) {
            return base.Channel.VerifyMultipleBVN(BVN, bankcode);
        }
        
        public System.Threading.Tasks.Task<string> VerifyMultipleBVNAsync(string BVN, string bankcode) {
            return base.Channel.VerifyMultipleBVNAsync(BVN, bankcode);
        }
        
        public string BVNUpdateCustomerDetails(kyc.bridge.api.BankBvnService.UpdateDetail myCustUpt, string bankcode) {
            return base.Channel.BVNUpdateCustomerDetails(myCustUpt, bankcode);
        }
        
        public System.Threading.Tasks.Task<string> BVNUpdateCustomerDetailsAsync(kyc.bridge.api.BankBvnService.UpdateDetail myCustUpt, string bankcode) {
            return base.Channel.BVNUpdateCustomerDetailsAsync(myCustUpt, bankcode);
        }
    }
}
